### ISSUE TITLE
Query on how to render chat avatars

### ISSUE THREAD

**Issue by cTheDragons** [crookedneighbor/habitica-avatar#1]
Hi!

With the latest update to Habitica where the Avatar image is embedded in the chat text now, I was wondering how to render the Avatar against image for my [Party and Group Display Tool](https://github.com/cTheDragons/Habitica-Party-Guild-Data-Tool). Is there a way to be able to either past the chat line object or the userStyles for it to render? 

Thanks

**Comment by crookedneighbor** [comment]
Can you provide a little more detail for this? I've lost context on what changes have happened recently.

**Comment by cTheDragons** [comment]
Thanks for your time with this. 

In group.chat each line now has userStyles which captures the Avatars features when the chat was placed. Currently the Habitica website is displaying the Avatar including any transformation, without background, mount, or pet per chat line.

**Comment by crookedneighbor** [comment]
Yep, this can definitely be done.

```js
var chatMessage = group.chat[0];

habiticaAvatar({
  container: selectorForWhereToInsertAvatar,
  user: chatMessage.userStyles
});
```
